### ISSUE TITLE
java.lang.IllegalStateException: XsltController#setMessageEmitter() is not supported for a configuration that allows multi-threading

### ISSUE THREAD

**Issue by eluija** [Armatiek/xslweb#4]
When running using Saxon-EE (9.9.1-7) with multi-threading activated we get following exception

java.lang.IllegalStateException: XsltController#setMessageEmitter() is not supported for a configuration that allows multi-threading. Use setMessageFactory() instead
  at net.sf.saxon.trans.XsltController.setMessageEmitter(XsltController.java:430)
  at nl.armatiek.xslweb.web.filter.PipelineGeneratorFilter.doFilter(PipelineGeneratorFilter.java:80)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at nl.armatiek.xslweb.web.filter.RequestSerializerFilter.doFilter(RequestSerializerFilter.java:79)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at nl.armatiek.xslweb.web.filter.WebAppFilter.doFilter(WebAppFilter.java:68)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at nl.armatiek.xslweb.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:60)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
  at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:748)

**Comment by maartenkroon** [comment]
@eluija : commit 525aac1 contains a fix. It is a little bit experimental because I don't have a Saxon EE 9.9 licence yet :-(, but the fix works in the HE version also.
